import React, { useState } from "react";
import { ScanResult } from "../types";
import { ScanGauge } from "./ScanGauge";
import {
  ShieldAlert,
  ShieldCheck,
  AlertTriangle,
  ExternalLink,
  Copy,
  Check,
  Download,
  Share2,
  RefreshCw,
  Server,
  Lock,
  Globe,
  FileText,
  Sparkles,
  Zap,
  ArrowRight,
  HelpCircle,
  Clock,
  ChevronRight,
  Info
} from "lucide-react";

interface ScanReportProps {
  result: ScanResult;
  onScanAnother: () => void;
}

export const ScanReport: React.FC<ScanReportProps> = ({ result, onScanAnother }) => {
  const [activeTab, setActiveTab] = useState<"indicators" | "ai" | "network" | "remediation">("indicators");
  const [copiedUrl, setCopiedUrl] = useState(false);
  const [copiedReport, setCopiedReport] = useState(false);
  const [showWarningModal, setShowWarningModal] = useState(false);

  const handleCopyUrl = () => {
    navigator.clipboard.writeText(result.url);
    setCopiedUrl(true);
    setTimeout(() => setCopiedUrl(false), 2000);
  };

  const handleCopyReport = () => {
    const reportText = `[PhisherFinder Threat Report]
URL: ${result.normalizedUrl}
Verdict: ${result.threatLevel} (Threat Index: ${result.threatScore}/100)
Classification: ${result.threatType}
Scanned: ${new Date(result.scannedAt).toUTCString()}
Summary: ${result.summary}
Indicators:
${result.indicators.map((i) => ` - [${i.status.toUpperCase()}] ${i.name}: ${i.detail}`).join("\n")}
Network:
 - IP: ${result.networkInfo.ip || "N/A"}
 - SSL: ${result.networkInfo.hasSsl ? "Enabled (HTTPS)" : "Insecure (HTTP)"}
 - DNS: ${result.networkInfo.dnsResolved ? "Resolved" : "Failed / Unresolved"}
`;
    navigator.clipboard.writeText(reportText);
    setCopiedReport(true);
    setTimeout(() => setCopiedReport(false), 2000);
  };

  const handleDownloadTextReport = () => {
    const reportText = `PHISHERFINDER THREAT INTELLIGENCE DOSSIER
=====================================================
Target URL: ${result.url}
Normalized: ${result.normalizedUrl}
Hostname: ${result.hostname}
Scan Timestamp: ${result.scannedAt}

VERDICT: ${result.verdict}
THREAT SCORE: ${result.threatScore} / 100
THREAT LEVEL: ${result.threatLevel}
THREAT CLASSIFICATION: ${result.threatType}
TARGETED BRAND: ${result.targetedBrand || "None detected"}

EXECUTIVE SUMMARY:
-----------------------------------------------------
${result.summary}

SECURITY INDICATORS DETECTED:
-----------------------------------------------------
${result.indicators
  .map(
    (i) =>
      `[${i.status.toUpperCase()}] ${i.name} (Severity: ${i.severity.toUpperCase()})\nDetail: ${i.detail}\n`
  )
  .join("\n")}

NETWORK & INFRASTRUCTURE:
-----------------------------------------------------
IP Address: ${result.networkInfo.ip || "Unresolved"}
Protocol: ${result.protocol}
DNS Resolution: ${result.networkInfo.dnsResolved ? "SUCCESSFUL" : "FAILED / NXDOMAIN"}
Redirect Hops: ${result.networkInfo.redirectCount}
${result.networkInfo.redirectChain.map((hop, idx) => `Hop ${idx + 1}: ${hop}`).join("\n")}

AI BEHAVIORAL ANALYSIS:
-----------------------------------------------------
${
  result.aiAnalysis
    ? `Psychological Urgency: ${result.aiAnalysis.urgencyScore}%\nTactics: ${result.aiAnalysis.socialEngineeringTactics.join(
        ", "
      )}\nRecommendation: ${result.aiAnalysis.recommendation}\nConfidence: ${result.aiAnalysis.confidence}%`
    : "Local Heuristic Engine Mode"
}

=====================================================
Report generated by PhisherFinder URL Security Engine.
`;
    const blob = new Blob([reportText], { type: "text/plain;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = `phisherfinder-report-${result.hostname}-${Date.now()}.txt`;
    link.click();
    URL.revokeObjectURL(url);
  };

  // Verdict Theme styling
  const isMalicious = result.verdict === "MALICIOUS";
  const isSuspicious = result.verdict === "SUSPICIOUS";
  const isLowRisk = result.verdict === "LOW_RISK";
  const isSafe = result.verdict === "SAFE";

  let bannerBorder = "border-emerald-500/30 bg-gradient-to-b from-emerald-950/30 to-slate-900/60";
  let verdictTextColor = "text-emerald-400";
  let verdictIcon = <ShieldCheck className="w-8 h-8 text-emerald-400" />;

  if (isMalicious) {
    bannerBorder = "border-rose-500/40 bg-gradient-to-b from-rose-950/40 to-slate-900/70";
    verdictTextColor = "text-rose-400";
    verdictIcon = <ShieldAlert className="w-8 h-8 text-rose-500" />;
  } else if (isSuspicious) {
    bannerBorder = "border-amber-500/40 bg-gradient-to-b from-amber-950/40 to-slate-900/70";
    verdictTextColor = "text-amber-400";
    verdictIcon = <AlertTriangle className="w-8 h-8 text-amber-500" />;
  } else if (isLowRisk) {
    bannerBorder = "border-yellow-500/40 bg-gradient-to-b from-yellow-950/40 to-slate-900/70";
    verdictTextColor = "text-yellow-400";
    verdictIcon = <Info className="w-8 h-8 text-yellow-400" />;
  }

  return (
    <div id="scan-report-container" className="w-full max-w-5xl mx-auto space-y-6 animate-fadeIn">
      {/* Top Banner Card */}
      <div className={`p-6 sm:p-8 rounded-2xl border ${bannerBorder} shadow-2xl relative backdrop-blur-md`}>
        <div className="flex flex-col lg:flex-row items-center justify-between gap-6">
          {/* Left: Verdict and details */}
          <div className="flex-1 space-y-4 text-center lg:text-left">
            <div className="flex flex-wrap items-center justify-center lg:justify-start gap-2.5">
              <span className="flex items-center gap-1.5 px-3 py-1 rounded-full text-xs font-bold uppercase tracking-wider bg-slate-800 text-slate-300 border border-slate-700">
                <Clock className="w-3 h-3 text-slate-400" />
                {new Date(result.scannedAt).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit", second: "2-digit" })}
              </span>

              <span
                className={`px-3 py-1 rounded-full text-xs font-bold uppercase tracking-wider border ${
                  isMalicious
                    ? "bg-rose-500/20 text-rose-300 border-rose-500/40"
                    : isSuspicious
                    ? "bg-amber-500/20 text-amber-300 border-amber-500/40"
                    : isLowRisk
                    ? "bg-yellow-500/20 text-yellow-300 border-yellow-500/40"
                    : "bg-emerald-500/20 text-emerald-300 border-emerald-500/40"
                }`}
              >
                {result.threatLevel}
              </span>

              {result.targetedBrand && (
                <span className="px-3 py-1 rounded-full text-xs font-bold bg-purple-500/20 text-purple-300 border border-purple-500/40">
                  Target: {result.targetedBrand}
                </span>
              )}
            </div>

            <div>
              <h1 className={`text-2xl sm:text-3xl font-extrabold tracking-tight ${verdictTextColor} flex items-center justify-center lg:justify-start gap-3`}>
                {verdictIcon}
                {isMalicious && "Malicious Phishing Detected"}
                {isSuspicious && "Suspicious Link Flagged"}
                {isLowRisk && "Low Risk Caution Advised"}
                {isSafe && "Verified Safe Web Link"}
              </h1>
              <p className="mt-2 text-slate-300 text-sm sm:text-base leading-relaxed max-w-2xl">
                {result.summary}
              </p>
            </div>

            {/* Target URL Display with copy button */}
            <div className="flex items-center gap-2 p-2.5 rounded-xl bg-slate-950/80 border border-slate-800 max-w-2xl">
              <span className="text-xs font-mono font-medium text-slate-400 px-2 py-0.5 rounded bg-slate-900 border border-slate-800 shrink-0">
                {result.protocol.toUpperCase()}
              </span>
              <span className="text-xs sm:text-sm font-mono text-slate-200 truncate flex-1 select-all" title={result.normalizedUrl}>
                {result.normalizedUrl}
              </span>
              <button
                id="btn-copy-url"
                onClick={handleCopyUrl}
                className="p-1.5 rounded-lg hover:bg-slate-800 text-slate-400 hover:text-white transition-colors"
                title="Copy URL"
              >
                {copiedUrl ? <Check className="w-4 h-4 text-emerald-400" /> : <Copy className="w-4 h-4" />}
              </button>
              <button
                id="btn-open-warning"
                onClick={() => setShowWarningModal(true)}
                className="p-1.5 rounded-lg hover:bg-slate-800 text-slate-400 hover:text-amber-400 transition-colors"
                title="Review & Visit"
              >
                <ExternalLink className="w-4 h-4" />
              </button>
            </div>
          </div>

          {/* Right: Gauge */}
          <div className="shrink-0 flex flex-col items-center">
            <ScanGauge score={result.threatScore} verdict={result.verdict} />
          </div>
        </div>

        {/* Action Row */}
        <div className="mt-6 pt-6 border-t border-slate-800/80 flex flex-wrap items-center justify-between gap-3">
          <div className="flex flex-wrap items-center gap-2">
            <button
              id="btn-copy-report"
              onClick={handleCopyReport}
              className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-slate-800/80 hover:bg-slate-800 text-xs font-semibold text-slate-200 transition-colors cursor-pointer"
            >
              {copiedReport ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Share2 className="w-3.5 h-3.5 text-slate-400" />}
              <span>{copiedReport ? "Report Copied" : "Share Report"}</span>
            </button>

            <button
              id="btn-download-report"
              onClick={handleDownloadTextReport}
              className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-slate-800/80 hover:bg-slate-800 text-xs font-semibold text-slate-200 transition-colors cursor-pointer"
            >
              <Download className="w-3.5 h-3.5 text-slate-400" />
              <span>Download Dossier</span>
            </button>
          </div>

          <button
            id="btn-scan-another"
            onClick={onScanAnother}
            className="flex items-center gap-1.5 px-4 py-2 rounded-xl bg-emerald-500 hover:bg-emerald-400 text-slate-950 font-bold text-xs transition-all shadow-md shadow-emerald-500/20 cursor-pointer"
          >
            <RefreshCw className="w-3.5 h-3.5" />
            <span>Scan Another URL</span>
          </button>
        </div>
      </div>

      {/* Tabs Navigation */}
      <div className="flex items-center gap-2 border-b border-slate-800 pb-2 overflow-x-auto">
        <button
          id="tab-indicators"
          onClick={() => setActiveTab("indicators")}
          className={`flex items-center gap-2 px-4 py-2 rounded-xl text-xs font-bold transition-all whitespace-nowrap cursor-pointer ${
            activeTab === "indicators"
              ? "bg-slate-800 text-emerald-400 border border-slate-700 shadow-sm"
              : "text-slate-400 hover:text-slate-200 hover:bg-slate-900 border border-transparent"
          }`}
        >
          <ShieldAlert className="w-4 h-4" />
          Threat Indicators ({result.indicators.length})
        </button>

        <button
          id="tab-ai"
          onClick={() => setActiveTab("ai")}
          className={`flex items-center gap-2 px-4 py-2 rounded-xl text-xs font-bold transition-all whitespace-nowrap cursor-pointer ${
            activeTab === "ai"
              ? "bg-slate-800 text-purple-400 border border-slate-700 shadow-sm"
              : "text-slate-400 hover:text-slate-200 hover:bg-slate-900 border border-transparent"
          }`}
        >
          <Sparkles className="w-4 h-4 text-purple-400" />
          AI Threat Intelligence
        </button>

        <button
          id="tab-network"
          onClick={() => setActiveTab("network")}
          className={`flex items-center gap-2 px-4 py-2 rounded-xl text-xs font-bold transition-all whitespace-nowrap cursor-pointer ${
            activeTab === "network"
              ? "bg-slate-800 text-cyan-400 border border-slate-700 shadow-sm"
              : "text-slate-400 hover:text-slate-200 hover:bg-slate-900 border border-transparent"
          }`}
        >
          <Server className="w-4 h-4" />
          Network & DNS Diagnostics
        </button>

        <button
          id="tab-remediation"
          onClick={() => setActiveTab("remediation")}
          className={`flex items-center gap-2 px-4 py-2 rounded-xl text-xs font-bold transition-all whitespace-nowrap cursor-pointer ${
            activeTab === "remediation"
              ? "bg-slate-800 text-amber-400 border border-slate-700 shadow-sm"
              : "text-slate-400 hover:text-slate-200 hover:bg-slate-900 border border-transparent"
          }`}
        >
          <Zap className="w-4 h-4 text-amber-400" />
          Emergency Safety Checklist
        </button>
      </div>

      {/* Tab 1: Threat Indicators */}
      {activeTab === "indicators" && (
        <div id="tab-content-indicators" className="space-y-4">
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            {result.indicators.map((ind, idx) => {
              const isPass = ind.status === "pass";
              const isDanger = ind.status === "danger";
              const isWarning = ind.status === "warning";

              return (
                <div
                  key={idx}
                  className={`p-4 rounded-xl border bg-slate-900/60 backdrop-blur-sm transition-all hover:bg-slate-900 ${
                    isDanger
                      ? "border-rose-500/40"
                      : isWarning
                      ? "border-amber-500/40"
                      : "border-slate-800"
                  }`}
                >
                  <div className="flex items-start justify-between gap-3">
                    <div className="flex items-center gap-2.5">
                      <div
                        className={`w-7 h-7 rounded-lg flex items-center justify-center shrink-0 ${
                          isDanger
                            ? "bg-rose-500/10 text-rose-400"
                            : isWarning
                            ? "bg-amber-500/10 text-amber-400"
                            : "bg-emerald-500/10 text-emerald-400"
                        }`}
                      >
                        {isDanger ? (
                          <ShieldAlert className="w-4 h-4" />
                        ) : isWarning ? (
                          <AlertTriangle className="w-4 h-4" />
                        ) : (
                          <Check className="w-4 h-4" />
                        )}
                      </div>
                      <div>
                        <h4 className="text-sm font-bold text-white leading-tight">
                          {ind.name}
                        </h4>
                        <span className="text-[11px] text-slate-400">
                          {ind.category}
                        </span>
                      </div>
                    </div>

                    <span
                      className={`text-[10px] font-bold uppercase tracking-wider px-2 py-0.5 rounded-full border ${
                        ind.severity === "critical"
                          ? "bg-rose-950 text-rose-300 border-rose-800"
                          : ind.severity === "high"
                          ? "bg-rose-950/60 text-rose-400 border-rose-900"
                          : ind.severity === "medium"
                          ? "bg-amber-950 text-amber-300 border-amber-800"
                          : ind.severity === "low"
                          ? "bg-yellow-950 text-yellow-300 border-yellow-800"
                          : "bg-emerald-950 text-emerald-300 border-emerald-900"
                      }`}
                    >
                      {ind.severity === "none" ? "CLEAN" : ind.severity}
                    </span>
                  </div>

                  <p className="mt-3 text-xs text-slate-300 leading-relaxed">
                    {ind.detail}
                  </p>
                </div>
              );
            })}
          </div>
        </div>
      )}

      {/* Tab 2: AI Threat Intelligence */}
      {activeTab === "ai" && (
        <div id="tab-content-ai" className="space-y-6">
          {result.aiAnalysis ? (
            <div className="p-6 rounded-2xl border border-purple-500/30 bg-purple-950/10 backdrop-blur-sm space-y-6">
              <div className="flex items-center gap-3">
                <div className="w-10 h-10 rounded-xl bg-purple-500/20 border border-purple-500/40 flex items-center justify-center text-purple-300">
                  <Sparkles className="w-5 h-5" />
                </div>
                <div>
                  <h3 className="text-lg font-bold text-white">
                    Gemini AI Threat Assessment
                  </h3>
                  <p className="text-xs text-purple-300">
                    Confidence Level: {result.aiAnalysis.confidence}% • Model: Gemini 3.8 Flash
                  </p>
                </div>
              </div>

              <div className="p-4 rounded-xl bg-slate-900/90 border border-slate-800">
                <span className="text-xs font-bold uppercase text-purple-400 tracking-wider">
                  Executive Threat Brief
                </span>
                <p className="mt-1 text-sm text-slate-200 leading-relaxed">
                  {result.aiAnalysis.summary}
                </p>
              </div>

              {/* Social Engineering Vectors Identified */}
              <div className="space-y-3">
                <span className="text-xs font-bold uppercase text-slate-300 tracking-wider">
                  Social Engineering Tactics Identified
                </span>
                <div className="flex flex-wrap gap-2">
                  {result.aiAnalysis.socialEngineeringTactics.map((tactic, idx) => (
                    <span
                      key={idx}
                      className="px-3 py-1 rounded-lg text-xs font-semibold bg-purple-500/15 text-purple-200 border border-purple-500/30 flex items-center gap-1.5"
                    >
                      <AlertTriangle className="w-3 h-3 text-purple-400" />
                      {tactic}
                    </span>
                  ))}
                </div>
              </div>

              {/* Psychological Urgency Score Bar */}
              <div className="space-y-1.5">
                <div className="flex justify-between text-xs font-semibold">
                  <span className="text-slate-300">Psychological Urgency Index</span>
                  <span className="text-purple-400 font-mono">{result.aiAnalysis.urgencyScore} / 100</span>
                </div>
                <div className="h-2 w-full bg-slate-900 rounded-full overflow-hidden border border-slate-800">
                  <div
                    className="h-full bg-gradient-to-r from-purple-500 to-rose-500 transition-all duration-700"
                    style={{ width: `${Math.min(100, Math.max(5, result.aiAnalysis.urgencyScore))}%` }}
                  />
                </div>
                <p className="text-[11px] text-slate-400">
                  Measures artificial urgency, panic triggers, or fear-based language commonly weaponized by phishing authors.
                </p>
              </div>

              {/* Recommendation */}
              <div className="p-4 rounded-xl bg-slate-900/90 border border-slate-800">
                <span className="text-xs font-bold uppercase text-emerald-400 tracking-wider">
                  Expert Safety Recommendation
                </span>
                <p className="mt-1 text-sm text-slate-200 leading-relaxed">
                  {result.aiAnalysis.recommendation}
                </p>
              </div>

              {/* Victim Protection Steps */}
              {result.aiAnalysis.victimActionSteps.length > 0 && (
                <div className="space-y-2">
                  <span className="text-xs font-bold uppercase text-amber-400 tracking-wider">
                    Recommended Containment Actions
                  </span>
                  <div className="space-y-2">
                    {result.aiAnalysis.victimActionSteps.map((step, idx) => (
                      <div
                        key={idx}
                        className="flex items-start gap-2.5 p-3 rounded-xl bg-slate-900/60 border border-slate-800/80 text-xs text-slate-200"
                      >
                        <span className="w-5 h-5 rounded-full bg-amber-500/10 text-amber-400 flex items-center justify-center font-mono font-bold text-[10px] shrink-0">
                          {idx + 1}
                        </span>
                        <span className="leading-relaxed">{step}</span>
                      </div>
                    ))}
                  </div>
                </div>
              )}
            </div>
          ) : (
            <div className="p-8 rounded-2xl border border-slate-800 bg-slate-900/50 text-center space-y-3">
              <Sparkles className="w-8 h-8 text-slate-500 mx-auto" />
              <h4 className="text-base font-bold text-white">AI Deep Inspection Telemetry</h4>
              <p className="text-xs text-slate-400 max-w-md mx-auto">
                Local heuristic engine has verified key signature rules. Gemini AI deep analysis is activated with your backend API key.
              </p>
            </div>
          )}
        </div>
      )}

      {/* Tab 3: Network & DNS Diagnostics */}
      {activeTab === "network" && (
        <div id="tab-content-network" className="space-y-6">
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
            <div className="p-4 rounded-xl border border-slate-800 bg-slate-900/60">
              <span className="text-[11px] font-semibold text-slate-400 uppercase tracking-wider">
                Resolved IP
              </span>
              <p className="mt-1 text-base font-bold font-mono text-cyan-300">
                {result.networkInfo.ip || "Unresolved (NXDOMAIN)"}
              </p>
            </div>

            <div className="p-4 rounded-xl border border-slate-800 bg-slate-900/60">
              <span className="text-[11px] font-semibold text-slate-400 uppercase tracking-wider">
                DNS Resolution
              </span>
              <p className="mt-1 text-base font-bold text-slate-100 flex items-center gap-1.5">
                {result.networkInfo.dnsResolved ? (
                  <>
                    <Check className="w-4 h-4 text-emerald-400" />
                    <span>Active Domain</span>
                  </>
                ) : (
                  <>
                    <ShieldAlert className="w-4 h-4 text-rose-400" />
                    <span>Unresolved / Inactive</span>
                  </>
                )}
              </p>
            </div>

            <div className="p-4 rounded-xl border border-slate-800 bg-slate-900/60">
              <span className="text-[11px] font-semibold text-slate-400 uppercase tracking-wider">
                SSL / TLS Security
              </span>
              <p className="mt-1 text-base font-bold text-slate-100 flex items-center gap-1.5">
                {result.networkInfo.hasSsl ? (
                  <>
                    <Lock className="w-4 h-4 text-emerald-400" />
                    <span>HTTPS Encrypted</span>
                  </>
                ) : (
                  <>
                    <AlertTriangle className="w-4 h-4 text-amber-400" />
                    <span>Insecure (HTTP)</span>
                  </>
                )}
              </p>
            </div>

            <div className="p-4 rounded-xl border border-slate-800 bg-slate-900/60">
              <span className="text-[11px] font-semibold text-slate-400 uppercase tracking-wider">
                Redirection Hops
              </span>
              <p className="mt-1 text-base font-bold font-mono text-slate-100">
                {result.networkInfo.redirectCount} {result.networkInfo.redirectCount === 1 ? "Hop" : "Hops"}
              </p>
            </div>
          </div>

          {/* Redirection Chain Visualizer */}
          <div className="p-6 rounded-2xl border border-slate-800 bg-slate-900/60 space-y-4">
            <h4 className="text-sm font-bold text-white flex items-center gap-2">
              <Globe className="w-4 h-4 text-cyan-400" />
              Redirection & Request Hop Tracer
            </h4>
            <div className="space-y-3">
              {result.networkInfo.redirectChain.map((hop, index) => (
                <div key={index} className="flex items-center gap-3">
                  <div className="flex items-center justify-center w-6 h-6 rounded-full bg-cyan-500/20 text-cyan-400 font-mono font-bold text-xs shrink-0">
                    {index + 1}
                  </div>
                  <div className="flex-1 p-2.5 rounded-lg bg-slate-950 border border-slate-800 font-mono text-xs text-slate-300 break-all">
                    {hop}
                  </div>
                  {index < result.networkInfo.redirectChain.length - 1 && (
                    <ArrowRight className="w-4 h-4 text-slate-600 shrink-0" />
                  )}
                </div>
              ))}
            </div>
          </div>

          {/* Detailed Structural Heuristics */}
          <div className="p-6 rounded-2xl border border-slate-800 bg-slate-900/60 space-y-3">
            <h4 className="text-sm font-bold text-white">Domain Structure Heuristics</h4>
            <div className="grid grid-cols-2 sm:grid-cols-3 gap-3 text-xs">
              <div className="p-3 rounded-lg bg-slate-950 border border-slate-800/80">
                <span className="text-slate-400">Entropy Score:</span>
                <p className="font-mono font-bold text-slate-200 mt-0.5">{result.heuristicDetails.entropyScore} bits</p>
              </div>
              <div className="p-3 rounded-lg bg-slate-950 border border-slate-800/80">
                <span className="text-slate-400">Subdomains:</span>
                <p className="font-mono font-bold text-slate-200 mt-0.5">{result.heuristicDetails.subdomainCount}</p>
              </div>
              <div className="p-3 rounded-lg bg-slate-950 border border-slate-800/80">
                <span className="text-slate-400">Homograph Attack:</span>
                <p className={`font-bold mt-0.5 ${result.heuristicDetails.isHomograph ? "text-rose-400" : "text-emerald-400"}`}>
                  {result.heuristicDetails.isHomograph ? "DETECTED" : "None"}
                </p>
              </div>
              <div className="p-3 rounded-lg bg-slate-950 border border-slate-800/80">
                <span className="text-slate-400">High-Risk TLD:</span>
                <p className={`font-bold mt-0.5 ${result.heuristicDetails.isHighRiskTld ? "text-amber-400" : "text-emerald-400"}`}>
                  {result.heuristicDetails.isHighRiskTld ? "Yes" : "No"}
                </p>
              </div>
              <div className="p-3 rounded-lg bg-slate-950 border border-slate-800/80">
                <span className="text-slate-400">Host Type:</span>
                <p className="font-bold text-slate-200 mt-0.5">
                  {result.heuristicDetails.isIpAddress ? "Raw IP Address" : "Registered Domain"}
                </p>
              </div>
              <div className="p-3 rounded-lg bg-slate-950 border border-slate-800/80">
                <span className="text-slate-400">Auth Spoofing (@):</span>
                <p className={`font-bold mt-0.5 ${result.heuristicDetails.hasObfuscatedChars ? "text-rose-400" : "text-emerald-400"}`}>
                  {result.heuristicDetails.hasObfuscatedChars ? "Present" : "None"}
                </p>
              </div>
            </div>
          </div>
        </div>
      )}

      {/* Tab 4: Remediation & Action Plan */}
      {activeTab === "remediation" && (
        <div id="tab-content-remediation" className="space-y-6">
          <div className="p-6 rounded-2xl border border-slate-800 bg-slate-900/60 space-y-6">
            <div>
              <h3 className="text-base font-bold text-white flex items-center gap-2">
                <Zap className="w-5 h-5 text-amber-400" />
                What To Do If You Interacted With This Link
              </h3>
              <p className="text-xs text-slate-400 mt-1">
                Follow this emergency cybersecurity response protocol based on your level of interaction.
              </p>
            </div>

            <div className="space-y-4">
              <div className="p-4 rounded-xl border border-slate-800 bg-slate-950 space-y-2">
                <h5 className="text-xs font-bold uppercase text-rose-400 flex items-center gap-1.5">
                  <AlertTriangle className="w-3.5 h-3.5" />
                  Scenario A: I entered my password, email, or credentials
                </h5>
                <ul className="text-xs text-slate-300 space-y-1.5 list-disc pl-5">
                  <li>
                    <strong>Change your password immediately</strong> on the official website of the impersonated service.
                  </li>
                  <li>
                    If you reuse that password on other accounts (Gmail, banks, social accounts), change them immediately as well.
                  </li>
                  <li>
                    Revoke active sessions and enforce <strong>Two-Factor Authentication (2FA)</strong> using an authenticator app (e.g. Google Authenticator), rather than SMS if possible.
                  </li>
                </ul>
              </div>

              <div className="p-4 rounded-xl border border-slate-800 bg-slate-950 space-y-2">
                <h5 className="text-xs font-bold uppercase text-amber-400 flex items-center gap-1.5">
                  <AlertTriangle className="w-3.5 h-3.5" />
                  Scenario B: I entered credit card or financial details
                </h5>
                <ul className="text-xs text-slate-300 space-y-1.5 list-disc pl-5">
                  <li>
                    Contact your bank or card issuer immediately via the phone number on the back of your card to freeze/replace the card.
                  </li>
                  <li>
                    Review recent transactions for micro-charges often tested by card-skimming operations.
                  </li>
                </ul>
              </div>

              <div className="p-4 rounded-xl border border-slate-800 bg-slate-950 space-y-2">
                <h5 className="text-xs font-bold uppercase text-cyan-400 flex items-center gap-1.5">
                  <AlertTriangle className="w-3.5 h-3.5" />
                  Scenario C: I clicked the link, but entered no information
                </h5>
                <ul className="text-xs text-slate-300 space-y-1.5 list-disc pl-5">
                  <li>
                    Clear your browser cache, cookies, and temporary site permissions for that domain.
                  </li>
                  <li>
                    Check your device’s downloads folder to confirm no silent payloads or `.apk`, `.exe`, or `.dmg` files were downloaded.
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </div>
      )}

      {/* Safety Warning Modal before external navigation */}
      {showWarningModal && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-950/80 backdrop-blur-md">
          <div className="w-full max-w-md p-6 rounded-2xl border border-rose-500/50 bg-slate-900 shadow-2xl space-y-4">
            <div className="flex items-center gap-3 text-rose-400">
              <ShieldAlert className="w-7 h-7" />
              <h3 className="text-lg font-bold">Safety Warning: Unsafe Destination</h3>
            </div>
            <p className="text-xs text-slate-300 leading-relaxed">
              PhisherFinder scanned <strong>{result.hostname}</strong> and assigned it a risk index of{" "}
              <strong className="text-rose-400">{result.threatScore}/100</strong>. Opening this link in a standard browser may expose your device to credential harvesting, drive-by downloads, or exploit kits.
            </p>
            <div className="p-3 rounded-lg bg-slate-950 border border-slate-800 font-mono text-[11px] text-slate-400 break-all">
              {result.normalizedUrl}
            </div>
            <div className="flex items-center justify-end gap-2 pt-2">
              <button
                onClick={() => setShowWarningModal(false)}
                className="px-4 py-2 rounded-xl bg-slate-800 hover:bg-slate-700 text-xs font-semibold text-slate-200 transition-colors cursor-pointer"
              >
                Go Back (Recommended)
              </button>
              <a
                href={result.normalizedUrl}
                target="_blank"
                rel="noreferrer noopener"
                onClick={() => setShowWarningModal(false)}
                className="px-4 py-2 rounded-xl bg-rose-600 hover:bg-rose-500 text-xs font-bold text-white transition-colors cursor-pointer"
              >
                Proceed Anyway
              </a>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};
